[tool.poetry]
name = "poetry-file"
version = "0.1.0"
description = ""
authors = ["Elsa Schutfort <a02392875@aggies.usu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
